name: Generate documentation
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: NPM install
        uses: jaid/action-npm-install@v1.2.1
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          config_file: ./.jsdoc.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs