name: Test

on: [push, pull_request]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: jaid/action-npm-install@v1.2.1
      - run: npm test